### ISSUE TITLE
Compatibility with Coq 8.6 / trunk

### ISSUE THREAD

**Issue by ejgallego** [JasonGross/bedrock#2]
Something strange in the Travis Coq build here:

https://travis-ci.org/ejgallego/coq/jobs/204977514

somehow the Coq mode gets reverted to 8.4, it is weird as I cannot reproduce locally. In my machine,
```
make src facade
```
fails with
```
File "./Bedrock/ILTac.v", line 17, characters 0-25:
Error: while loading
/home/emilio/external/coq-master/bedrock/Bedrock/reification/reif.cmxs:
no implementation available for Tacinterp
```
which again for some reason is strange, as if it was not using the proper `coq_makefile`.

**Comment by JasonGross** [comment]
First thought: we do feature testing on OCaml code; if the constant we're testing for moved, 8.7 might look the same as 8.4.

I'm confused by that error message; does this happen on a fresh clone?  Do you need to open Ltac_plugin or something?

**Comment by JasonGross** [comment]
@ejgallego I recently fixed an issue in trunk similar to this by opening Ltac_plugin in the right places.  Is this still an issue, or is it fixed now?

**Comment by ejgallego** [comment]
I think this is fixed and your diagnostic was correct.
